/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import DAO.ParticipaçãoDAO;
import javax.swing.JOptionPane;
import model.Doação;
import model.Evento;
import model.Função;

/**
 *
 * @author Ingryd Salinas
 */
public class TelaParticipar extends javax.swing.JPanel {

    /**
     * Creates new form TelaParticipar
     */
    
    private Evento evento;
    
    public TelaParticipar(Evento evento) {
        initComponents();
        this.evento = evento;
        carregarComboBoxFuncoes();
    }

    //Método que preenche a combo box com dados do banco
    public void carregarComboBoxFuncoes() {

        // Limpa e Povoa o Combo de Funções
        cbbFuncao.removeAllItems();
        
        model.Função placeholder = new model.Função();
        placeholder.setNome("Selecione");
        placeholder.setId(0);
        cbbFuncao.addItem(placeholder); // Adiciona o objeto inicial seguro
        
        DAO.FunçãoDAO dao = new DAO.FunçãoDAO();
        for (model.Função f : dao.listarTodas()) {
            cbbFuncao.addItem(f); // Alimenta com os dados vindos do banco
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblLocalidade = new javax.swing.JLabel();
        lblCpf = new javax.swing.JLabel();
        txtCpf = new javax.swing.JTextField();
        lblFuncao = new javax.swing.JLabel();
        cbbFuncao = new javax.swing.JComboBox<>();
        btnCancelar = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        txtData = new javax.swing.JTextField();
        lblCpf1 = new javax.swing.JLabel();

        lblLocalidade.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblLocalidade.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLocalidade.setText("PREENCHA OS DADOS PARA PARTICIPAR");

        lblCpf.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblCpf.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCpf.setText("DATA");

        txtCpf.addActionListener(this::txtCpfActionPerformed);

        lblFuncao.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblFuncao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFuncao.setText("FUNÇÃO");

        cbbFuncao.addActionListener(this::cbbFuncaoActionPerformed);

        btnCancelar.setBackground(new java.awt.Color(0, 0, 0));
        btnCancelar.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setText("CANCELAR");
        btnCancelar.addActionListener(this::btnCancelarActionPerformed);

        btnSalvar.setBackground(new java.awt.Color(0, 0, 0));
        btnSalvar.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnSalvar.setForeground(new java.awt.Color(255, 255, 255));
        btnSalvar.setText("SALVAR");
        btnSalvar.addActionListener(this::btnSalvarActionPerformed);

        txtData.addActionListener(this::txtDataActionPerformed);

        lblCpf1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblCpf1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCpf1.setText("CPF");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lblCpf, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                    .addComponent(lblFuncao, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                    .addComponent(lblCpf1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbbFuncao, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(lblLocalidade, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(175, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(lblLocalidade, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCpf1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbbFuncao, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFuncao, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(68, 68, 68))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(101, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtCpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCpfActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        String cpf = txtCpf.getText().trim();
    
        // Validação básica se o campo CPF estiver vazio
        if (cpf.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Digite o CPF usado na inscrição para poder cancelar!");
            return;
        }

        Função funcao = (Função) cbbFuncao.getSelectedItem();

        if (funcao == null || funcao.getId() == 0) {
            JOptionPane.showMessageDialog(this,
                "Selecione a função que deseja cancelar!");
            return;
        }
        
        // Caixa de diálogo perguntando "Tem certeza?" para evitar cliques por engano
        int confirmacao = JOptionPane.showConfirmDialog(this, 
                "Tem certeza que deseja cancelar sua participação neste evento?", 
                "Confirmar Cancelamento", 
                JOptionPane.YES_NO_OPTION);

        if (confirmacao == JOptionPane.YES_OPTION) {
            ParticipaçãoDAO dao = new ParticipaçãoDAO();
            dao.cancelarParticipacao(cpf, this.evento.getId(), funcao.getId());
        }
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        // 1. Captura os campos fixos da tela
        String cpf = txtCpf.getText();
        String data = txtData.getText(); 

        if (cpf.isEmpty() || data.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, preencha o CPF e a Data!");
            return;
        }
        
        Doação d = new Doação(); 
        d.setUsuCpf(cpf);
        d.setData(data);
        d.setEvento(this.evento); // Passa o evento atual recebido no construtor
        
        Função funcaoSelecionada = (Função) cbbFuncao.getSelectedItem();
        if (funcaoSelecionada.getId() == 0) {
            JOptionPane.showMessageDialog(this, "Selecione uma função válida!");
            return;
        }
        d.setFunção(funcaoSelecionada);
        d.setDescricao("Função atribuída: " + funcaoSelecionada.getNome());
        
        // 3. Com o "d" totalmente montado, enviamos ele para o DAO salvar no banco
        ParticipaçãoDAO dao = new ParticipaçãoDAO();
        dao.escolherCargo(d); // <--- Passando o d preenchido para o banco
    
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void txtDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDataActionPerformed

    private void cbbFuncaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbFuncaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbbFuncaoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox<model.Função> cbbFuncao;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCpf;
    private javax.swing.JLabel lblCpf1;
    private javax.swing.JLabel lblFuncao;
    private javax.swing.JLabel lblLocalidade;
    private javax.swing.JTextField txtCpf;
    private javax.swing.JTextField txtData;
    // End of variables declaration//GEN-END:variables
}
