/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import DAO.DoaçãoDAO;
import javax.swing.JOptionPane;
import model.Doação;
import model.Evento;
import model.Insumo;
import model.Utensilio;

/**
 *
 * @author Ingryd Salinas
 */
public class TelaDoar extends javax.swing.JPanel {

    /**
     * Creates new form TelaDoar
     */
    
    private Evento evento;
    
    public TelaDoar(Evento evento) {
        initComponents();
        this.evento = evento;
        
        // Oculta os labels e os campos específicos ao iniciar
        lblValor.setVisible(false);
        txtValor.setVisible(false);
    
        lblInsumo.setVisible(false);
        cbbInsumo.setVisible(false);
        lblQtdInsumo.setVisible(false);
        spnQtdInsumo.setVisible(false);
    
        lblUtensilio.setVisible(false);
        cbbUtensilios.setVisible(false);
        lblQtdUtensilio.setVisible(false);
        spnQtdUtensilio.setVisible(false);
        
        carregarCombos();
    }
    
    public void carregarCombos() {
        
        // 1. Limpa e Povoa o Combo de Insumos
        cbbInsumo.removeAllItems();
    
        model.Insumo placeholderInsumo = new model.Insumo();
        placeholderInsumo.setNome("Selecione");
        placeholderInsumo.setId(0);
        cbbInsumo.addItem(placeholderInsumo); // Adiciona o objeto inicial seguro

        DAO.InsumoDAO insDAO = new DAO.InsumoDAO();
        for (model.Insumo i : insDAO.listarTodos()) 
            cbbInsumo.addItem(i); // Alimenta com os dados vindos do banco

        // 2. Limpa e Povoa o Combo de Utensílios
        cbbUtensilios.removeAllItems();
    
        model.Utensilio placeholderUte = new model.Utensilio();
        placeholderUte.setNome("Selecione");
        placeholderUte.setId(0);
        cbbUtensilios.addItem(placeholderUte); // Adiciona o objeto inicial seguro

        DAO.UtensilioDAO uteDAO = new DAO.UtensilioDAO();
        for (model.Utensilio u : uteDAO.listarTodos()) 
            cbbUtensilios.addItem(u); // Alimenta com os dados vindos do banco
    
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        lblLocalidade = new javax.swing.JLabel();
        lblCpf = new javax.swing.JLabel();
        txtCpf = new javax.swing.JTextField();
        lblUtensilio = new javax.swing.JLabel();
        cbbUtensilios = new javax.swing.JComboBox<>();
        btnSalvar = new javax.swing.JButton();
        lblValor = new javax.swing.JLabel();
        txtValor = new javax.swing.JTextField();
        lblQtdUtensilio = new javax.swing.JLabel();
        cbbInsumo = new javax.swing.JComboBox<>();
        lblCpf1 = new javax.swing.JLabel();
        lblCpf2 = new javax.swing.JLabel();
        txtData = new javax.swing.JTextField();
        rdbInsumo = new javax.swing.JRadioButton();
        rdbDinheiro = new javax.swing.JRadioButton();
        rdbUtensilio = new javax.swing.JRadioButton();
        lblInsumo = new javax.swing.JLabel();
        lblQtdInsumo = new javax.swing.JLabel();
        spnQtdInsumo = new javax.swing.JSpinner();
        spnQtdUtensilio = new javax.swing.JSpinner();

        lblLocalidade.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblLocalidade.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLocalidade.setText("PREENCHA OS DADOS PARA DOAR");

        lblCpf.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblCpf.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCpf.setText("CPF");

        txtCpf.addActionListener(this::txtCpfActionPerformed);

        lblUtensilio.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblUtensilio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUtensilio.setText("UTENSÍLIO");

        btnSalvar.setBackground(new java.awt.Color(0, 0, 0));
        btnSalvar.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnSalvar.setForeground(new java.awt.Color(255, 255, 255));
        btnSalvar.setText("SALVAR");
        btnSalvar.addActionListener(this::btnSalvarActionPerformed);

        lblValor.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblValor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblValor.setText("VALOR");

        txtValor.addActionListener(this::txtValorActionPerformed);

        lblQtdUtensilio.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblQtdUtensilio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblQtdUtensilio.setText("QUANTIDADE");

        lblCpf1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblCpf1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCpf1.setText("DATA");

        lblCpf2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblCpf2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCpf2.setText("<html>TIPO<br>DE <br>DOAÇÃO</html>");

        txtData.addActionListener(this::txtDataActionPerformed);

        buttonGroup1.add(rdbInsumo);
        rdbInsumo.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        rdbInsumo.setText("INSUMO");
        rdbInsumo.addActionListener(this::rdbInsumoActionPerformed);

        buttonGroup1.add(rdbDinheiro);
        rdbDinheiro.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        rdbDinheiro.setText("DINHEIRO");
        rdbDinheiro.addActionListener(this::rdbDinheiroActionPerformed);

        buttonGroup1.add(rdbUtensilio);
        rdbUtensilio.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        rdbUtensilio.setText("UTENSÍLIO");
        rdbUtensilio.addActionListener(this::rdbUtensilioActionPerformed);

        lblInsumo.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblInsumo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInsumo.setText("INSUMO");

        lblQtdInsumo.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblQtdInsumo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblQtdInsumo.setText("QUANTIDADE");

        spnQtdInsumo.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        spnQtdInsumo.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        spnQtdUtensilio.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        spnQtdUtensilio.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(235, 235, 235)
                        .addComponent(lblLocalidade, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(lblUtensilio, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                                .addComponent(lblCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblCpf1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblValor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblCpf2))
                            .addComponent(lblInsumo, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbbUtensilios, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbbInsumo, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(rdbDinheiro)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(rdbInsumo)
                                .addGap(46, 46, 46)
                                .addComponent(rdbUtensilio))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(106, 106, 106)
                                .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblQtdUtensilio, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(spnQtdUtensilio, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblQtdInsumo, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(spnQtdInsumo, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(171, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lblLocalidade, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCpf1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(lblCpf2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rdbDinheiro)
                            .addComponent(rdbInsumo)
                            .addComponent(rdbUtensilio))))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblValor, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbbInsumo, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblInsumo, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblQtdInsumo, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spnQtdInsumo))
                .addGap(65, 65, 65)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbbUtensilios, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUtensilio, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblQtdUtensilio, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spnQtdUtensilio))
                .addGap(60, 60, 60)
                .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(79, Short.MAX_VALUE))
        );

        spnQtdInsumo.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(129, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtCpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCpfActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        
        // 1. Pega os campos fixos da tela
        String cpf = txtCpf.getText().trim();
        String data = txtData.getText().trim();

        if (cpf.isEmpty() || data.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, preencha o CPF e a Data!");
            return;
        }

        // ==========================================================
        // AQUI NASCE O "d": Criamos o objeto Doação na memória
        // ==========================================================
        Doação d = new Doação(); 
        d.setUsuCpf(cpf);
        d.setData(data);
        d.setEvento(this.evento); // Passa o evento atual recebido no construtor
        
        // 1. Verifica se é Dinheiro
        if (rdbDinheiro.isSelected()) {
            d.setValor(Double.parseDouble(txtValor.getText().trim()));
            d.setDescricao("Doação em Dinheiro");

        // 2. SE NÃO FOR DINHEIRO, verifica se é Insumo
        } else if (rdbInsumo.isSelected()) {
            Insumo insumoSelecionado = (Insumo) cbbInsumo.getSelectedItem();
            if (insumoSelecionado.getId() == 0) {
                JOptionPane.showMessageDialog(this, "Selecione um Insumo válido!");
                return;
            }
            d.setInsumo(insumoSelecionado);
            int quantidade = (int) spnQtdInsumo.getValue();
            d.setQuantidade(quantidade);
            d.setDescricao("Doação de Insumo: " + insumoSelecionado.getNome());
            

        // 3. SE NÃO FOR NENHUM DOS DOIS, verifica se é Utensílio
        } else if (rdbUtensilio.isSelected()) {
            Utensilio utensilioSelecionado = (Utensilio) cbbUtensilios.getSelectedItem();
            if (utensilioSelecionado.getId() == 0) {
                JOptionPane.showMessageDialog(this, "Selecione um Utensílio válido!");
                return;
            }
            d.setUtensilio(utensilioSelecionado);
            int quantidade = (int) spnQtdUtensilio.getValue();
            d.setQuantidade(quantidade);
            d.setDescricao("Doação de Utensílio: " + utensilioSelecionado.getNome());

        // 4. SE NÃO FOR NENHUM, avisa o usuário
        } else {
            JOptionPane.showMessageDialog(this, "Por favor, selecione um Tipo de Doação!");
            return;
        }
        
        // 3. Com o "d" totalmente montado, enviamos ele para o DAO salvar no banco
        DoaçãoDAO dao = new DoaçãoDAO();
        dao.registrarDoacao(d); // <--- Passando o d preenchido para o banco
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void txtValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtValorActionPerformed

    private void txtDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDataActionPerformed

    private void rdbInsumoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbInsumoActionPerformed
        // Exibe insumo
        lblInsumo.setVisible(true);
        cbbInsumo.setVisible(true);
        lblQtdInsumo.setVisible(true);
        spnQtdInsumo.setVisible(true);
    
        // Oculta os outros
        lblValor.setVisible(false);
        txtValor.setVisible(false);
        lblUtensilio.setVisible(false);
        cbbUtensilios.setVisible(false);
        lblQtdUtensilio.setVisible(false);
        spnQtdUtensilio.setVisible(false);
    
        this.revalidate();
        this.repaint();
    }//GEN-LAST:event_rdbInsumoActionPerformed

    private void rdbDinheiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbDinheiroActionPerformed
        // Exibe dinheiro
        lblValor.setVisible(true);
        txtValor.setVisible(true);
    
        // Oculta os outros
        lblInsumo.setVisible(false);
        cbbInsumo.setVisible(false);
        lblQtdInsumo.setVisible(false);
        spnQtdInsumo.setVisible(false);
        lblUtensilio.setVisible(false);
        cbbUtensilios.setVisible(false);
        lblQtdUtensilio.setVisible(false);
        spnQtdUtensilio.setVisible(false);
    
        // Força o Java a redesenhar a tela com os novos tamanhos
        this.revalidate();
        this.repaint();
    }//GEN-LAST:event_rdbDinheiroActionPerformed

    private void rdbUtensilioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbUtensilioActionPerformed
        // Exibe utensílio
        lblUtensilio.setVisible(true);
        cbbUtensilios.setVisible(true);
        lblQtdUtensilio.setVisible(true);
        spnQtdUtensilio.setVisible(true);
    
        // Oculta os outros
        lblValor.setVisible(false);
        txtValor.setVisible(false);
        lblInsumo.setVisible(false);
        cbbInsumo.setVisible(false);
        spnQtdInsumo.setVisible(false);
        lblQtdInsumo.setVisible(false);
    
        this.revalidate();
        this.repaint();
    }//GEN-LAST:event_rdbUtensilioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalvar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<model.Insumo> cbbInsumo;
    private javax.swing.JComboBox<model.Utensilio> cbbUtensilios;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCpf;
    private javax.swing.JLabel lblCpf1;
    private javax.swing.JLabel lblCpf2;
    private javax.swing.JLabel lblInsumo;
    private javax.swing.JLabel lblLocalidade;
    private javax.swing.JLabel lblQtdInsumo;
    private javax.swing.JLabel lblQtdUtensilio;
    private javax.swing.JLabel lblUtensilio;
    private javax.swing.JLabel lblValor;
    private javax.swing.JRadioButton rdbDinheiro;
    private javax.swing.JRadioButton rdbInsumo;
    private javax.swing.JRadioButton rdbUtensilio;
    private javax.swing.JSpinner spnQtdInsumo;
    private javax.swing.JSpinner spnQtdUtensilio;
    private javax.swing.JTextField txtCpf;
    private javax.swing.JTextField txtData;
    private javax.swing.JTextField txtValor;
    // End of variables declaration//GEN-END:variables
}
