/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import DAO.EventoDAO;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Evento;

/**
 *
 * @author Ingryd Salinas, Isabela Cordeiro
 */
public class TelaVisualizarEvento extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaVisualizarEvento.class.getName());

    /**
     * Creates new form TelaVisualizarEvento
     */
    public TelaVisualizarEvento() {
        initComponents();
        preencherTabela();//método no construtor para a tabela não iniciar vazia
    }
        
    public Evento obterEventoSelecionado() {

        int linha = tblEvento.getSelectedRow();

        if (linha == -1)
            return null; // Nenhuma linha foi clicada
    

        Evento evento = new Evento();
        // Pega os dados diretamente das colunas da JTable
        evento.setId(Integer.parseInt(tblEvento.getValueAt(linha, 0).toString()));
        evento.setNome(tblEvento.getValueAt(linha, 1).toString());
        evento.setStatus(tblEvento.getValueAt(linha, 2).toString());
        evento.setData(tblEvento.getValueAt(linha, 3).toString());
        evento.setRua(tblEvento.getValueAt(linha, 4).toString());
        evento.setNumero(tblEvento.getValueAt(linha, 5).toString());
        evento.setBairro(tblEvento.getValueAt(linha, 6).toString());
        evento.setCidade(tblEvento.getValueAt(linha, 7).toString());
        evento.setUf(tblEvento.getValueAt(linha, 8).toString());

        return evento;
    }
    
    //Método para criar o object, ou seja, insere linhas na tabela com dados do BD
    public void preencherTabela(){
        // 1. Instancia o DAO para buscar os dados do MySQL
        EventoDAO dao = new EventoDAO();
        ArrayList<Evento> lista = dao.listarTodos();
    
        // 2. Captura o modelo da sua JTable tblEvento
        DefaultTableModel modelo = (DefaultTableModel) tblEvento.getModel();
    
        // 3. Limpa a tabela para não duplicar os dados caso clique duas vezes
        modelo.setNumRows(0);
    
        // 4. Varre o ArrayList criando o Object[] para cada evento
        for (Evento e : lista) {
            Object[] linha = new Object[]{
                e.getId(),
                e.getNome(),
                e.getStatus(),
                e.getData(),
                e.getRua(),
                e.getNumero(),
                e.getBairro(),
                e.getCidade(),
                e.getUf()
            };
        
            // 5. Adiciona a linha preenchida na tabela visual
            modelo.addRow(linha);
        }//fim for
    }//fim preencherTabela
    
    private void atualizarTabela(String busca){

        DAO.EventoDAO dao = new DAO.EventoDAO();

        ArrayList<Evento> lista = dao.listarBusca(busca);

        javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) tblEvento.getModel();

        modelo.setNumRows(0);

        for(model.Evento e : lista){

            modelo.addRow(new Object[]{
                e.getId(),
                e.getNome(),
                e.getStatus(),
                e.getData(),
                e.getRua(),
                e.getNumero(),
                e.getBairro(),
                e.getCidade(),
                e.getUf()
            });

        }

    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblLocalidade = new javax.swing.JLabel();
        txtBusca = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEvento = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        btnBuscar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        btnDoar = new javax.swing.JButton();
        btnParticipar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblLocalidade.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblLocalidade.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLocalidade.setText("Localidade:");

        txtBusca.addActionListener(this::txtBuscaActionPerformed);

        tblEvento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "N° Evento", "Nome", "Status", "Data", "Rua", "N°", "Bairro", "Cidade", "UF"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblEvento);

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(this::btnBuscarActionPerformed);

        btnDoar.setBackground(new java.awt.Color(0, 0, 0));
        btnDoar.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnDoar.setForeground(new java.awt.Color(255, 255, 255));
        btnDoar.setText("DOAR");
        btnDoar.addActionListener(this::btnDoarActionPerformed);

        btnParticipar.setBackground(new java.awt.Color(0, 0, 0));
        btnParticipar.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnParticipar.setForeground(new java.awt.Color(255, 255, 255));
        btnParticipar.setText("PARTICIPAR");
        btnParticipar.addActionListener(this::btnParticiparActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnParticipar, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(btnDoar, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(472, 472, 472))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDoar, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnParticipar, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(254, 254, 254)
                .addComponent(lblLocalidade, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnBuscar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(70, 70, 70))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 39, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1280, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblLocalidade, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBuscar))
                        .addGap(42, 42, 42)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(107, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDoarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoarActionPerformed
        Evento eventoSelecionado = obterEventoSelecionado();

        if (eventoSelecionado == null) {
            JOptionPane.showMessageDialog(this, "Selecione um evento primeiro!");
            return;
        }
    
        // 1. Cria a instância do JPanel passando o evento
        TelaDoar tela = new TelaDoar(eventoSelecionado);
    
        // 2. Cria uma janela JDialog flutuante passando 'this' (a tela atual) como dona
        // O parâmetro 'true' ativa o modo MODAL (bloqueia a tela de trás)
        javax.swing.JDialog janelaPopUp = new javax.swing.JDialog(this, " ", true);
    
        // 3. Coloca o painel dentro da nova janela
        janelaPopUp.add(tela);
    
        // 4. Ajusta o tamanho da janela de acordo com o tamanho do painel
        janelaPopUp.pack();
    
        // 5. Centraliza o pop-up no meio do monitor
        janelaPopUp.setLocationRelativeTo(this);
    
        // 6. Exibe a janela na tela
        janelaPopUp.setVisible(true);
    }//GEN-LAST:event_btnDoarActionPerformed

    private void btnParticiparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnParticiparActionPerformed
        
        Evento eventoSelecionado = obterEventoSelecionado();
    
        if(eventoSelecionado == null){
            JOptionPane.showMessageDialog(this, "Selecione um evento primeiro!");
            return;
        }
      
        // 1. Cria a instância do JPanel passando o evento
        TelaParticipar tela = new TelaParticipar(eventoSelecionado);

        // 2. Cria uma janela JDialog flutuante passando 'this' (a tela atual) como dona
        // O parâmetro 'true' ativa o modo MODAL (bloqueia a tela de trás)
        javax.swing.JDialog janelaPopUp = new javax.swing.JDialog(this, " ", true);
        
        // 3. Coloca o seu painel dentro dessa nova janela
        janelaPopUp.add(tela);
        
        // 4. Ajusta o tamanho da janela de acordo com o tamanho do seu painel
        janelaPopUp.pack();
        
        // 5. Centraliza o pop-up no meio do monitor
        janelaPopUp.setLocationRelativeTo(this);
        
        // 6. Exibe a janela na tela
        janelaPopUp.setVisible(true);
    }//GEN-LAST:event_btnParticiparActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        
        String busca = txtBusca.getText();

        atualizarTabela(busca);
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void txtBuscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaVisualizarEvento().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnDoar;
    private javax.swing.JButton btnParticipar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblLocalidade;
    private javax.swing.JTable tblEvento;
    private javax.swing.JTextField txtBusca;
    // End of variables declaration//GEN-END:variables

}
